import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import Description from "@/components/description";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Toaster } from "react-hot-toast";
import AppSection from "@/components/appRecomend/App";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
       

        <Header />
<Toaster/>
        <main className=" " style={{
          
         maxWidth: 1320, margin: "0 auto", padding: "0 20px" 
      }}>{children}

        </main>
        <AppSection/>
        <Description/>
        <Footer />
      </body>
    </html>
  );
}
