import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/layout/header";
import Footer from "@/layout/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
         maxWidth: 1320, margin: "0 auto", padding: "0 20px" 
      }}>
       

        <Header />
     
        <main className=" ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
